apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cekit-build-and-push
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cekit-build
spec:
  params:
  - name: CEKIT_IMAGE
    description: Reference to the built images (specified in the CEkit `image.yaml` file)
  - name: CEKIT_IMAGE_TAG
    description: Tag for the image created by CEkit
  - name: CEKIT_BUILD_IMAGE
    description: The location of the CEkit builder image.
  - name: CEKIT_BUILD_TARGET
    description: Target runtime for CEkit builds
    type: string
    default: "podman"
  - name: CEKIT_BUILD_DIR
    description: Directory with CEkit `image.yaml` file
    default: "."
  - name: BUILD_EXTRA_ARGS
    description: Extra parameters passed for the build command when building images.
    default: ""
  - name: TLSVERIFY
    description: Verify the TLS on the registry endpoint
    default: "true"
  - name: PUSH_EXTRA_ARGS
    description: Extra parameters passed for the push command when pushing images.
    type: string
    default: ""
  workspaces:
  - name: source

  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  - name: IMAGE_URL
    description: Name of the image just built.

  steps:
  - name: build
    image: $(params.CEKIT_BUILD_IMAGE)
    workingDir: $(workspaces.source.path)/$(params.CEKIT_BUILD_DIR)
    script: |
      cekit build $(params.CEKIT_BUILD_TARGET)
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
      capabilities:
        add: ["SETFCAP"]

  - name: push
    image: $(params.CEKIT_BUILD_IMAGE)
    workingDir: $(workspaces.source.path)
    script: |
      podman push \
        $(params.PUSH_EXTRA_ARGS) --tls-verify=$(params.TLSVERIFY) \
        --digestfile $(workspaces.source.path)/image-digest \
        $(params.CEKIT_IMAGE):$(params.CEKIT_IMAGE_TAG)
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
      capabilities:
        add: ["SETFCAP"]
    

  - name: digest-to-results
    image: $(params.CEKIT_BUILD_IMAGE)
    script: cat $(workspaces.source.path)/image-digest | tee /tekton/results/IMAGE_DIGEST

  - name: name-to-results
    image: $(params.CEKIT_BUILD_IMAGE)
    script: echo $(params.CEKIT_IMAGE):$(params.CEKIT_IMAGE_TAG) | tee /tekton/results/IMAGE_URL